# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 or uno ide 1.0
# BOARD_TAG    = mega2560
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
CXXFLAGS_STD = -std=c++11 -Wall -Wextra -pedantic
include ./Arduino-Makefile/Arduino.mk
